#!/usr/bin/env ansible-playbook

- hosts: apt
  tasks:
    - name: apt install
      apt:
        update_cache: yes
        name: "{{pkg}}"

- hosts: yum
  tasks:
    - name: yum install
      yum:
        update_cache: yes
        name: "{{pkg}}"

- hosts: dnf
  tasks:
    - name: dnf install
      dnf:
        name: "{{pkg}}"
