#!/usr/bin/env ansible-playbook

- name: apt install
  hosts: apt
  tasks:
    - name: apt install
      apt:
        update_cache: yes
        name: "{{pkg}}"

- name: yum install
  hosts: yum
  tasks:
    - name: yum install
      yum:
        update_cache: yes
        name: "{{pkg}}"

- name: dnf install
  hosts: dnf
  tasks:
    - name: dnf install
      dnf:
        name: "{{pkg}}"
