#!/usr/bin/env ansible-playbook

- name: start machines
  hosts: localhost
  strategy: free
  tasks:

    - name: render template
      tags: render
      template:
        src: templates/docker-compose.yml
        dest: "docker-compose.yml"
        force: yes

    - name: docker-compose down
      command: >
        docker-compose --verbose --log-level DEBUG
        down --remove-orphans

    - name: docker-compose up
      # we want fresh images, always recreate
      command: >
        docker-compose --verbose --log-level DEBUG
        up --force-recreate --detach

- name: run raw cmd to init containers
  hosts: docker
  tasks:
    - raw: "{{raw_cmd}}"

- name: run setup to check
  hosts: all
  tasks:
    - setup:
